Export proof to textual Hilbert style (for circom)
Pi-Squared-Network/pi2 pull request #776
Opened 2024-01-23 09:01 UTC by traiansf

2024-01-24 12:16 UTC, nishantjr reviewed
Could you add a couple of tests? Perhaps just the output of `phi -> phi` intitially?

2024-01-24 12:16 UTC, nishantjr commented on generation/src/proof_generation/interpreter/hilbert_interpreter.py
> +        self.proof: list[HilbertStep] = []
@traiansf This storing of proofs will work for small proofs such as Propositional, but will likely get into trouble for longer executions. Would it be easy to "stream" the output so we don't need to do this?

2024-01-25 07:05 UTC, mcalancea commented on generation/src/proof_generation/interpreter/hilbert_interpreter.py
> +        self.proof: list[HilbertStep] = []
@nishantjr
We're aware of this issue in general, but I think for our current use cases it's a good compromise to store everything explicitly. It's less work and the Circom checker needs more insight to handle the proof rules that would make the larger proofs approachable anyway.

2024-01-30 08:11 UTC, mcalancea requested changes
Great work, Traian! Left some comments.

2024-01-30 08:11 UTC, mcalancea commented on generation/src/proof_generation/interpreter/hilbert_interpreter.py
> +    def publish_axiom(self, axiom: Pattern) -> None:
This handling of axioms feels sketchy. If we don't handle any Hilbert proofs using axioms yet, let's raise an Error here and note to consider it more carefully once we do. 

The thing is that `publish_axiom` and `publish_claim` are executed in the Gamma/Claim phases and those aren't really proofs, but "constructions". Now you do indeed need some way to get the axioms you'll be using in the Proof phase inside the interpreter, but it's not clear to me that _this_ interpreter will always (or even should) run the Gamma phase beforehand. It makes sense to grab them (via constructor) from the `ProofExp` class instead I think?  

@nishantjr please comment on this.

2024-01-30 12:36 UTC, traiansf commented on generation/src/proof_generation/interpreter/hilbert_interpreter.py
> +    def publish_axiom(self, axiom: Pattern) -> None:
I've added code to provide more intelligible messages for errors which would arise from the Axioms phase not being called here: https://github.com/Pi-Squared-Network/pi2/blob/74ed4295cced4ca05bb0fc5ca229d74aa4a9fd51/generation/src/proof_generation/interpreter/hilbert_interpreter.py#L193

2024-01-31 11:25 UTC, MirceaS approved these changes

2024-01-31 13:00 UTC, fiedlr requested changes

2024-01-31 13:00 UTC, fiedlr commented on generation/src/proof_generation/interpreter/hilbert_interpreter.py
> +        self.prop = 0
```suggestion
        self.previous_step_prop_type = 0
```

2024-01-31 13:00 UTC, fiedlr commented on generation/src/proof_generation/interpreter/hilbert_interpreter.py
> +        self.prop: int = 0
```suggestion
        self.previous_step_prop_type: int = 0
```

2024-02-01 11:28 UTC, traiansf commented on generation/src/proof_generation/interpreter/hilbert_interpreter.py
> +    """index: exists x, x"""
Unfortunately I had it mixed with (Existence)...

2024-02-01 15:44 UTC, mcalancea reviewed
Looks good to me, letting Adam approve.

2024-02-01 17:56 UTC, fiedlr approved these changes
Looks great! Thanks for addressing my suggestions. 

I just left a couple of minor ideas that might help and shouldn't be too hard to fix, but it's up to you if you want to implement them.

2024-02-01 17:56 UTC, fiedlr commented on generation/src/proof_generation/interpreter/hilbert_interpreter.py
> +    index: (exists arg2, phi1) -> phi2 (== conclusion)
`arg2 should be free in phi1`

This could be checked in `__post_init__`

2024-02-01 17:56 UTC, fiedlr commented on generation/src/proof_generation/interpreter/hilbert_interpreter.py
> +        super().__init__(index, conclusion)
This does not need to be here, does it?

2024-02-01 17:56 UTC, fiedlr commented on generation/src/proof_generation/interpreter/hilbert_interpreter.py
> +        super().__init__(index, conclusion)
I guess it does not need to have the dataclass decorator, as it's not introducing new arguments

2024-02-01 17:56 UTC, fiedlr commented on generation/src/proof_generation/interpreter/hilbert_interpreter.py
> +class HilbertProof:
I guess this could be an unfrozen dataclass

2024-02-01 17:56 UTC, fiedlr commented on generation/src/proof_generation/interpreter/hilbert_interpreter.py
> +    ExistsGeneralization = 6
Are these reflecting instruction numbers? Maybe they should eventually?

2024-02-01 17:56 UTC, fiedlr commented on generation/src/proof_generation/interpreter/hilbert_interpreter.py
> +                delta[i] = MetaVar(i)
Maybe this could actually be extracted to `utils.py` or something

2024-02-01 17:56 UTC, fiedlr commented on generation/src/proof_generation/interpreter/hilbert_interpreter.py
> +    def register_proof_step_conclusion(self, current_conclusion: Pattern) -> None:
I guess `register_proof_step_conclusion` should be called after adding to proof steps, and should take `current_conclusion` from the proof step where `index` is pointing (since `HilbertStep` has a conclusion too)

This will make it less likely to register something that does not match anything in the proof

2024-02-01 17:57 UTC, fiedlr commented on generation/src/proof_generation/interpreter/hilbert_interpreter.py
> +    index: (exists arg2, phi1) -> phi2 (== conclusion)
Not sure if this is doable in the current implementation though

2024-02-02 10:12 UTC, traiansf commented on generation/src/proof_generation/interpreter/hilbert_interpreter.py
> +    index: (exists arg2, phi1) -> phi2 (== conclusion)
The way it's done now, the best way to check it would probably to have a check function in HilbertProof which goes over the entire proof and checks it for consistency.

2024-02-02 10:23 UTC, mcalancea approved these changes

2024-02-02 11:22 UTC, merged